listen:
  host: 0.0.0.0
  port: 8192

storage:
  dir: /opt/notebooks

kernels:
  scala:
    language: scala
    scalaVersion: "2.12"
    classPath:
      - "/opt/spark/jars/*"
    env:
      SPARK_HOME: /opt/spark
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    spark:
      master: local[*]
      appName: Polynote
